name = "Owen"
uuid = "a159c9be-0176-11ea-0d64-b53c1d07f8ae"
authors = ["Chen Huang <chen1huang2@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
